---
- name: Initial Housekeeping 
  hosts: all_virts
  gather_facts: no
  tasks:
  - name: Load Variables
    include_vars:
      file: yml_out/routers.yml
      name: systems
    vars:
      system: 'j'
  - name: debug
    debug:
      msg: "{{ system }}"
  - name: Create router Directories
    file:
      path: "{{ build_dir }}/{{ inventory_hostname }}"
      state: directory
  - name: Build the Router Configs
    template: src=router_config/templates/main_template.j2 dest={{ build_dir }}/{{ "{{ build_dir }}/{{ inventory_hostname }}" }}/main.conf

#- name: Assemble the Config Fragments
#  assemble:
#    src: "{{ build_dir }}/{{ inventory_hostname }}"
#    dest: "{{ out_dir }}/{{ inventory_hostname }}.conf"